dry-run: null
hookfiles: "./hooks*.js"
language: nodejs
sandbox: false
server: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: html
output: [report.html]
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: ../../apiary.apib
endpoint: 'http://localhost:8080/cybercaptor-server'
